### ISSUE TITLE
Pod Install Question

### ISSUE THREAD

**Issue by rt2zz** [BranchMetrics/React-Native-Deep-Linking-SDK#2]
Why is pod install called from within node_modules. This seems to install the pod into the Branch.xcodeproj rather than my parent proj. If this is the case, then how would you go about deployment? In this case it seems preferable that the pod is installed upon `npm install`.

Let me know if I misunderstand the situation or what the reco is.

**Comment by bsy** [comment]
+1, my interim solution is to add a `postinstall` script hook in my top level RN package.json to run  `cd node_modules/react-native-branch-sdk; pod install`.

**Comment by aaustin** [comment]
Hey guys - Super sorry for the lack of response on our side. We don't have an engineer covering this repo so it's a bit dead in the water until we can hire someone. In the interim, you'll have to make due with it as is. Sorry!

**Comment by rt2zz** [comment]
Thanks, closing for now, will PR with an alternative
