### ISSUE TITLE
Cannot convert argument to string: Error Domain=RCTErrorDomain Code=0"Invalid type in JSON write (NSURLError)"

### ISSUE THREAD

**Issue by gnestor** [BranchMetrics/React-Native-Deep-Linking-SDK#7]
```
2016-04-08 18:35:54.606 [error][tid:com.facebook.React.JavaScript][RCTJSCExecutor.m:428] Cannot convert argument to string: Error Domain=RCTErrorDomain Code=0 "Invalid type in JSON write (NSURLError)" UserInfo={NSLocalizedDescription=Invalid type in JSON write (NSURLError)}
2016-04-08 18:35:54.633 [fatal][tid:com.facebook.React.JavaScript] Invalid type in JSON write (NSURLError)
```

To reproduce: 

* Install this library into a React Native project and set up the SDK following [these instructions](https://dev.branch.io/getting-started/sdk-integration-guide/guide/react/) 
  * Specifically add this line to `didFinishLaunchingWithOptions`: `[RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];`
* Simulate no network connection (turn on Airplane Mode or wifi if testing in Simulator)
* Call `branch.getFirstReferringParams()` or `branch.getLatestReferringParams()`

When I comment out the `initSessionWithLaunchOptions` line, the app doesn't crash. So, it appears that the `initSessionWithLaunchOptions` method is receiving a something other than a string when it's expecting a string. More importantly though, I still get deeplink data even with `initSessionWithLaunchOptions` commented out, so I'm wondering why this method is even necessary?

**Comment by magus** [comment]
It's your lucky day, I just finished writing a PR to fix this and was coming to open an issue when I saw this. I'll close this issue out in my PR commit.

**Comment by gnestor** [comment]
Nice work! So, is `init` needed? BTW, nice work on react-native-facebook-login 👍

**Comment by gnestor** [comment]
Thanks @magus. To whom it's concerned, this fix has been merged into a new repo https://github.com/BranchMetrics/react-native-branch which will soon replace this repo. @rt2zz Reminder that anyone using this repo or installing the SDK via NPM are most likely crashing their apps when network connection is unavailable.

**Comment by rt2zz** [comment]
@gnestor thanks for updating here. Yes we will be officially deprecating this repo and moving over to the new one shortly. The npm package name is changing however, so it will require some modification for consumers. I will publish complete instructions soon.

In the meantime lets leave this open so as to not confuse the situation.

**Comment by rt2zz** [comment]
Incidentally it appears that PR introduced another bug because notificationObject[@"error"] is sometimes a NSError and other times a NSString.

This variable typing is probably an upstream bug, but it is also something easy to check for and catch here ([preliminary solution here](https://github.com/BranchMetrics/react-native-branch/commit/e4157df418adfe9039993d0186832a3122c51268))

Tracking issue here: https://github.com/BranchMetrics/react-native-branch/issues/1
